// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetConfigDumpRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigDumpRequest) Reset()         { *m = GetConfigDumpRequest{} }
func (m *GetConfigDumpRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigDumpRequest) ProtoMessage()    {}
func (*GetConfigDumpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{0}
}

func (m *GetConfigDumpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigDumpRequest.Unmarshal(m, b)
}
func (m *GetConfigDumpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigDumpRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigDumpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigDumpRequest.Merge(m, src)
}
func (m *GetConfigDumpRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigDumpRequest.Size(m)
}
func (m *GetConfigDumpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigDumpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigDumpRequest proto.InternalMessageInfo

type GetConfigDumpResponse struct {
	Payload              string   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigDumpResponse) Reset()         { *m = GetConfigDumpResponse{} }
func (m *GetConfigDumpResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigDumpResponse) ProtoMessage()    {}
func (*GetConfigDumpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{1}
}

func (m *GetConfigDumpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigDumpResponse.Unmarshal(m, b)
}
func (m *GetConfigDumpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigDumpResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigDumpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigDumpResponse.Merge(m, src)
}
func (m *GetConfigDumpResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigDumpResponse.Size(m)
}
func (m *GetConfigDumpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigDumpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigDumpResponse proto.InternalMessageInfo

func (m *GetConfigDumpResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type TroubleShootingResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TroubleShootingResponse) Reset()         { *m = TroubleShootingResponse{} }
func (m *TroubleShootingResponse) String() string { return proto.CompactTextString(m) }
func (*TroubleShootingResponse) ProtoMessage()    {}
func (*TroubleShootingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{2}
}

func (m *TroubleShootingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TroubleShootingResponse.Unmarshal(m, b)
}
func (m *TroubleShootingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TroubleShootingResponse.Marshal(b, m, deterministic)
}
func (m *TroubleShootingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TroubleShootingResponse.Merge(m, src)
}
func (m *TroubleShootingResponse) XXX_Size() int {
	return xxx_messageInfo_TroubleShootingResponse.Size(m)
}
func (m *TroubleShootingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TroubleShootingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TroubleShootingResponse proto.InternalMessageInfo

func (m *TroubleShootingResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *TroubleShootingResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type TroubleShootingRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TroubleShootingRequest) Reset()         { *m = TroubleShootingRequest{} }
func (m *TroubleShootingRequest) String() string { return proto.CompactTextString(m) }
func (*TroubleShootingRequest) ProtoMessage()    {}
func (*TroubleShootingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{3}
}

func (m *TroubleShootingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TroubleShootingRequest.Unmarshal(m, b)
}
func (m *TroubleShootingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TroubleShootingRequest.Marshal(b, m, deterministic)
}
func (m *TroubleShootingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TroubleShootingRequest.Merge(m, src)
}
func (m *TroubleShootingRequest) XXX_Size() int {
	return xxx_messageInfo_TroubleShootingRequest.Size(m)
}
func (m *TroubleShootingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TroubleShootingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TroubleShootingRequest proto.InternalMessageInfo

func (m *TroubleShootingRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetConfigDumpRequest)(nil), "api.GetConfigDumpRequest")
	proto.RegisterType((*GetConfigDumpResponse)(nil), "api.GetConfigDumpResponse")
	proto.RegisterType((*TroubleShootingResponse)(nil), "api.TroubleShootingResponse")
	proto.RegisterType((*TroubleShootingRequest)(nil), "api.TroubleShootingRequest")
}

func init() { proto.RegisterFile("api/service.proto", fileDescriptor_42c32aec9010f89c) }

var fileDescriptor_42c32aec9010f89c = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e,
	0x2c, 0xc8, 0x54, 0x12, 0xe3, 0x12, 0x71, 0x4f, 0x2d, 0x71, 0xce, 0xcf, 0x4b, 0xcb, 0x4c, 0x77,
	0x29, 0xcd, 0x2d, 0x08, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x32, 0xe4, 0x12, 0x45, 0x13,
	0x2f, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x92, 0xe0, 0x62, 0x2f, 0x48, 0xac, 0xcc, 0xc9, 0x4f,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0x82, 0xb8, 0xc4, 0x43, 0x8a,
	0xf2, 0x4b, 0x93, 0x72, 0x52, 0x83, 0x33, 0xf2, 0xf3, 0x4b, 0x32, 0xf3, 0xd2, 0xe1, 0x9a, 0x64,
	0xb9, 0xb8, 0x8a, 0x20, 0x06, 0xc7, 0x67, 0xc2, 0xf4, 0x71, 0x42, 0x45, 0x3c, 0x53, 0x90, 0xcd,
	0x64, 0x42, 0x35, 0xd3, 0x9c, 0x4b, 0x0c, 0xc3, 0x4c, 0xb0, 0x2e, 0x02, 0x46, 0x1a, 0x65, 0x70,
	0x49, 0xf9, 0xa6, 0x16, 0x67, 0x40, 0x35, 0x17, 0x43, 0x35, 0x07, 0x43, 0x02, 0x40, 0xc8, 0x8b,
	0x8b, 0x17, 0xc5, 0x77, 0x42, 0x92, 0x7a, 0x89, 0x05, 0x99, 0x7a, 0xd8, 0x42, 0x42, 0x4a, 0x0a,
	0x9b, 0x14, 0xc4, 0x5f, 0x4a, 0x0c, 0x06, 0x8c, 0x46, 0x79, 0x5c, 0xd2, 0x01, 0x45, 0xf9, 0x15,
	0x95, 0x38, 0xac, 0xf2, 0xe7, 0xe2, 0x41, 0x96, 0x11, 0x92, 0x01, 0x1b, 0x87, 0x23, 0xa0, 0xa4,
	0xa4, 0xb1, 0xcb, 0x42, 0xe2, 0x84, 0x41, 0x83, 0xd1, 0x80, 0xd1, 0x89, 0x35, 0x0a, 0x14, 0x71,
	0x49, 0x6c, 0xe0, 0x48, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x68, 0x83, 0xa3, 0xd9,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MeshTroubleshootingServiceClient is the client API for MeshTroubleshootingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MeshTroubleshootingServiceClient interface {
	GetConfigDump(ctx context.Context, in *GetConfigDumpRequest, opts ...grpc.CallOption) (MeshTroubleshootingService_GetConfigDumpClient, error)
}

type meshTroubleshootingServiceClient struct {
	cc *grpc.ClientConn
}

func NewMeshTroubleshootingServiceClient(cc *grpc.ClientConn) MeshTroubleshootingServiceClient {
	return &meshTroubleshootingServiceClient{cc}
}

func (c *meshTroubleshootingServiceClient) GetConfigDump(ctx context.Context, in *GetConfigDumpRequest, opts ...grpc.CallOption) (MeshTroubleshootingService_GetConfigDumpClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MeshTroubleshootingService_serviceDesc.Streams[0], "/api.MeshTroubleshootingService/GetConfigDump", opts...)
	if err != nil {
		return nil, err
	}
	x := &meshTroubleshootingServiceGetConfigDumpClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MeshTroubleshootingService_GetConfigDumpClient interface {
	Recv() (*GetConfigDumpResponse, error)
	grpc.ClientStream
}

type meshTroubleshootingServiceGetConfigDumpClient struct {
	grpc.ClientStream
}

func (x *meshTroubleshootingServiceGetConfigDumpClient) Recv() (*GetConfigDumpResponse, error) {
	m := new(GetConfigDumpResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MeshTroubleshootingServiceServer is the server API for MeshTroubleshootingService service.
type MeshTroubleshootingServiceServer interface {
	GetConfigDump(*GetConfigDumpRequest, MeshTroubleshootingService_GetConfigDumpServer) error
}

// UnimplementedMeshTroubleshootingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMeshTroubleshootingServiceServer struct {
}

func (*UnimplementedMeshTroubleshootingServiceServer) GetConfigDump(req *GetConfigDumpRequest, srv MeshTroubleshootingService_GetConfigDumpServer) error {
	return status.Errorf(codes.Unimplemented, "method GetConfigDump not implemented")
}

func RegisterMeshTroubleshootingServiceServer(s *grpc.Server, srv MeshTroubleshootingServiceServer) {
	s.RegisterService(&_MeshTroubleshootingService_serviceDesc, srv)
}

func _MeshTroubleshootingService_GetConfigDump_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetConfigDumpRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MeshTroubleshootingServiceServer).GetConfigDump(m, &meshTroubleshootingServiceGetConfigDumpServer{stream})
}

type MeshTroubleshootingService_GetConfigDumpServer interface {
	Send(*GetConfigDumpResponse) error
	grpc.ServerStream
}

type meshTroubleshootingServiceGetConfigDumpServer struct {
	grpc.ServerStream
}

func (x *meshTroubleshootingServiceGetConfigDumpServer) Send(m *GetConfigDumpResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MeshTroubleshootingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MeshTroubleshootingService",
	HandlerType: (*MeshTroubleshootingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetConfigDump",
			Handler:       _MeshTroubleshootingService_GetConfigDump_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/service.proto",
}

// ProxyTroubleshootingServiceClient is the client API for ProxyTroubleshootingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyTroubleshootingServiceClient interface {
	Troubleshoot(ctx context.Context, opts ...grpc.CallOption) (ProxyTroubleshootingService_TroubleshootClient, error)
}

type proxyTroubleshootingServiceClient struct {
	cc *grpc.ClientConn
}

func NewProxyTroubleshootingServiceClient(cc *grpc.ClientConn) ProxyTroubleshootingServiceClient {
	return &proxyTroubleshootingServiceClient{cc}
}

func (c *proxyTroubleshootingServiceClient) Troubleshoot(ctx context.Context, opts ...grpc.CallOption) (ProxyTroubleshootingService_TroubleshootClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProxyTroubleshootingService_serviceDesc.Streams[0], "/api.ProxyTroubleshootingService/Troubleshoot", opts...)
	if err != nil {
		return nil, err
	}
	x := &proxyTroubleshootingServiceTroubleshootClient{stream}
	return x, nil
}

type ProxyTroubleshootingService_TroubleshootClient interface {
	Send(*TroubleShootingResponse) error
	Recv() (*TroubleShootingRequest, error)
	grpc.ClientStream
}

type proxyTroubleshootingServiceTroubleshootClient struct {
	grpc.ClientStream
}

func (x *proxyTroubleshootingServiceTroubleshootClient) Send(m *TroubleShootingResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *proxyTroubleshootingServiceTroubleshootClient) Recv() (*TroubleShootingRequest, error) {
	m := new(TroubleShootingRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProxyTroubleshootingServiceServer is the server API for ProxyTroubleshootingService service.
type ProxyTroubleshootingServiceServer interface {
	Troubleshoot(ProxyTroubleshootingService_TroubleshootServer) error
}

// UnimplementedProxyTroubleshootingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProxyTroubleshootingServiceServer struct {
}

func (*UnimplementedProxyTroubleshootingServiceServer) Troubleshoot(srv ProxyTroubleshootingService_TroubleshootServer) error {
	return status.Errorf(codes.Unimplemented, "method Troubleshoot not implemented")
}

func RegisterProxyTroubleshootingServiceServer(s *grpc.Server, srv ProxyTroubleshootingServiceServer) {
	s.RegisterService(&_ProxyTroubleshootingService_serviceDesc, srv)
}

func _ProxyTroubleshootingService_Troubleshoot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProxyTroubleshootingServiceServer).Troubleshoot(&proxyTroubleshootingServiceTroubleshootServer{stream})
}

type ProxyTroubleshootingService_TroubleshootServer interface {
	Send(*TroubleShootingRequest) error
	Recv() (*TroubleShootingResponse, error)
	grpc.ServerStream
}

type proxyTroubleshootingServiceTroubleshootServer struct {
	grpc.ServerStream
}

func (x *proxyTroubleshootingServiceTroubleshootServer) Send(m *TroubleShootingRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *proxyTroubleshootingServiceTroubleshootServer) Recv() (*TroubleShootingResponse, error) {
	m := new(TroubleShootingResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ProxyTroubleshootingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ProxyTroubleshootingService",
	HandlerType: (*ProxyTroubleshootingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Troubleshoot",
			Handler:       _ProxyTroubleshootingService_Troubleshoot_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/service.proto",
}
