apiVersion: v1
kind: Namespace
metadata:
  name: echo
spec:
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: apiserver
  namespace: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: echo
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: echo-server
        image: gcr.io/jianfeih-test/ts-server:0108a
        # image: docker.io/yanxue/http2-server
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: echo
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9000
  selector:
    apiserver: "true"
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.echo.example.com
spec:
  insecureSkipTLSVerify: true
  group: echo.example.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: echo
  version: v1alpha1