apiVersion: v1
kind: Service
metadata:
  name: istio-pilot{{ .Values.version }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: pilot
    release: {{ .Release.Name }}
    istio: pilot
spec:
  ports:
  - port: 15010
    name: grpc-xds # direct
  - port: 15011
    name: https-xds # mTLS
  - port: 15012
    name: https-dns # mTLS with k8s-signed cert
  - port: 8080
    name: http-legacy-discovery # direct
  - port: 15014
    name: http-monitoring
  - port: 443
    name: https-inject
    targetPort: 15017
  selector:
    {{- if ne .Values.version ""}}
    app: pilot
    version: {{ .Values.version }}
    {{ else }}
    istio: pilot
    {{- end }}
---
